### ISSUE TITLE
Support improperly formated TNB

### ISSUE THREAD

**Issue by cazino** [JDaren/subtitleConverter#32]
Hi, 

I got a stl file with an improperly formatted TNB :
The decoded string of the TNB is '1163 ' (with a space at the end), when it should be '01163'.
This leads the following stack trace 
`java.lang.NumberFormatException: For input string: "1163 "
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at subtitleFile.FormatSTL.parseFile(FormatSTL.java:87)
        at Convert.main(Convert.java:54)
subtitleFile.FatalParsingException: Format error in the file, migth be due to corrupt data.
For input string: "1163 "
        at subtitleFile.FormatSTL.parseFile(FormatSTL.java:185)
        at Convert.main(Convert.java:54)
`

Would you consider a PR that could fix the issue (even though I don't know yet how I can deal with this, advices are welcome) ? 

Thank you.

**Comment by cazino** [comment]
I guess the fix could just be :
`int numberOfTTIBlocks = Integer.parseInt(new String(tnb).strip());`

**Comment by cazino** [comment]
Actually the TNB was just the tip of the iceberg. 
The main problem with the STL file I am using is user data. It goes fine I strip user data form the STL, otherwise it crashes with :
`java.lang.NullPointerException
        at subtitleFile.FormatSTL.parseTextForSTL(FormatSTL.java:428)
        at subtitleFile.FormatSTL.parseFile(FormatSTL.java:161)
        at Convert.main(Convert.java:57)
subtitleFile.FatalParsingException: Format error in the file, migth be due to corrupt data.
null
        at subtitleFile.FormatSTL.parseFile(FormatSTL.java:185)
        at Convert.main(Convert.java:57)
`
Is it a known problem that you lib does not handle STL with user data ?

Regards.

**Comment by JDaren** [comment]
It is now. This is not professional software, but a university project I keep around in the hopes it may prove useful to someone. However, truth be told, it has not aged well and I haven't worked on it for years.

**Comment by JDaren** [comment]
Should I close this?

**Comment by cazino** [comment]
Yes , thanks for the merge !
